In [1]:
from pathlib import Path

input_dir = Path("/kaggle/input")

print("Pastas disponíveis na entrada do notebook:")

for pasta in input_dir.iterdir():
    print("-", pasta)

Pastas disponíveis na entrada do notebook:
- /kaggle/input/datasets

In [2]:
pastas_encontradas = []

for pasta in input_dir.rglob("chest_xray"):
    possui_train = (pasta / "train").exists()
    possui_val = (pasta / "val").exists()
    possui_test = (pasta / "test").exists()

    if possui_train and possui_val and possui_test:
        pastas_encontradas.append(pasta)
        print("Estrutura do dataset encontrada em:")
        print(pasta)

Estrutura do dataset encontrada em:
/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray
Estrutura do dataset encontrada em:
/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/chest_xray
Estrutura do dataset encontrada em:
/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/__MACOSX/chest_xray

In [3]:
base_dir = pastas_encontradas[0]

divisoes = ["train", "val", "test"]
classes = ["NORMAL", "PNEUMONIA"]

for divisao in divisoes:
    print(f"\n{divisao.upper()}")

    for classe in classes:
        pasta_classe = base_dir / divisao / classe

        arquivos = [
            arquivo
            for arquivo in pasta_classe.iterdir()
            if arquivo.is_file()
        ]

        quantidade = len(arquivos)

        print(f"{classe}: {quantidade} imagens")

TRAIN
NORMAL: 1341 imagens
PNEUMONIA: 3875 imagens

VAL
NORMAL: 8 imagens
PNEUMONIA: 8 imagens

TEST
NORMAL: 234 imagens
PNEUMONIA: 390 imagens

In [4]:
from pathlib import Path

import pandas as pd
from PIL import Image

In [5]:
caminhos_candidatos = [
    Path(
        "/kaggle/input/datasets/"
        "paultimothymooney/chest-xray-pneumonia/"
        "chest_xray"
    ),
    Path(
        "/kaggle/input/datasets/"
        "paultimothymooney/chest-xray-pneumonia/"
        "chest_xray/chest_xray"
    ),
    Path(
        "/kaggle/input/datasets/"
        "paultimothymooney/chest-xray-pneumonia/"
        "chest_xray/__MACOSX/chest_xray"
    ),
]

divisoes = ["train", "val", "test"]
classes = ["NORMAL", "PNEUMONIA"]
extensoes_validas = {".jpg", ".jpeg", ".png"}

In [6]:
comparacao_caminhos = []

for caminho_base in caminhos_candidatos:
    total_caminho = 0

    for divisao in divisoes:
        for classe in classes:
            pasta_classe = caminho_base / divisao / classe

            if pasta_classe.exists():
                arquivos = [
                    arquivo
                    for arquivo in pasta_classe.iterdir()
                    if arquivo.is_file()
                    and arquivo.suffix.lower() in extensoes_validas
                    and not arquivo.name.startswith("._")
                ]

                quantidade = len(arquivos)
            else:
                quantidade = 0

            total_caminho += quantidade

            comparacao_caminhos.append(
                {
                    "caminho": str(caminho_base),
                    "divisao": divisao,
                    "classe": classe,
                    "quantidade": quantidade,
                }
            )

    print("=" * 80)
    print("Caminho:", caminho_base)
    print("Total de imagens válidas:", total_caminho)

================================================================================
Caminho: /kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray
Total de imagens válidas: 5856
================================================================================
Caminho: /kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/chest_xray
Total de imagens válidas: 5856
================================================================================
Caminho: /kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/__MACOSX/chest_xray
Total de imagens válidas: 0

In [7]:
df_comparacao = pd.DataFrame(comparacao_caminhos)

tabela_comparacao = df_comparacao.pivot_table(
    index="caminho",
    columns=["divisao", "classe"],
    values="quantidade",
    fill_value=0,
)

tabela_comparacao

divisao                                              test             train  \
classe                                             NORMAL PNEUMONIA  NORMAL
caminho
/kaggle/input/datasets/paultimothymooney/chest-...  234.0     390.0  1341.0
/kaggle/input/datasets/paultimothymooney/chest-...    0.0       0.0     0.0
/kaggle/input/datasets/paultimothymooney/chest-...  234.0     390.0  1341.0

divisao                                                         val
classe                                             PNEUMONIA NORMAL PNEUMONIA
caminho
/kaggle/input/datasets/paultimothymooney/chest-...    3875.0    8.0       8.0
/kaggle/input/datasets/paultimothymooney/chest-...       0.0    0.0       0.0
/kaggle/input/datasets/paultimothymooney/chest-...    3875.0    8.0       8.0

In [8]:
base_dir = Path(
    "/kaggle/input/datasets/"
    "paultimothymooney/chest-xray-pneumonia/"
    "chest_xray"
)

print("Pasta oficial definida:")
print(base_dir)

print("\nA pasta existe?")
print(base_dir.exists())

Pasta oficial definida:
/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray

A pasta existe?
True

In [9]:
registros = []

for divisao in divisoes:
    for classe in classes:
        pasta_classe = base_dir / divisao / classe

        for arquivo in sorted(pasta_classe.iterdir()):
            arquivo_valido = (
                arquivo.is_file()
                and arquivo.suffix.lower() in extensoes_validas
                and not arquivo.name.startswith("._")
            )

            if arquivo_valido:
                registros.append(
                    {
                        "caminho": str(arquivo),
                        "nome_arquivo": arquivo.name,
                        "divisao_original": divisao,
                        "classe": classe,
                        "extensao": arquivo.suffix.lower(),
                    }
                )

inventario = pd.DataFrame(registros)

print("Quantidade de imagens registradas:")
print(len(inventario))

inventario.head()

Quantidade de imagens registradas:
5856

,caminho,nome_arquivo,divisao_original,classe,extensao
0,/kaggle/input/datasets/paultimothymooney/chest...,IM-0115-0001.jpeg,train,NORMAL,.jpeg
1,/kaggle/input/datasets/paultimothymooney/chest...,IM-0117-0001.jpeg,train,NORMAL,.jpeg
2,/kaggle/input/datasets/paultimothymooney/chest...,IM-0119-0001.jpeg,train,NORMAL,.jpeg
3,/kaggle/input/datasets/paultimothymooney/chest...,IM-0122-0001.jpeg,train,NORMAL,.jpeg
4,/kaggle/input/datasets/paultimothymooney/chest...,IM-0125-0001.jpeg,train,NORMAL,.jpeg

In [10]:
resumo_divisao_classe = (
    inventario
    .groupby(["divisao_original", "classe"])
    .size()
    .unstack(fill_value=0)
)

resumo_divisao_classe["TOTAL"] = resumo_divisao_classe.sum(axis=1)

resumo_divisao_classe

classe            NORMAL  PNEUMONIA  TOTAL
divisao_original
test                 234        390    624
train               1341       3875   5216
val                    8          8     16

In [11]:
resumo_classes = (
    inventario["classe"]
    .value_counts()
    .rename_axis("classe")
    .reset_index(name="quantidade")
)

resumo_classes["percentual"] = (
    resumo_classes["quantidade"]
    / resumo_classes["quantidade"].sum()
    * 100
).round(2)

resumo_classes

      classe  quantidade  percentual
0  PNEUMONIA        4273       72.97
1     NORMAL        1583       27.03

In [12]:
nomes_repetidos = (
    inventario
    .groupby("nome_arquivo")
    .agg(
        quantidade=("caminho", "size"),
        classes=("classe", lambda valores: ", ".join(sorted(set(valores)))),
        divisoes=(
            "divisao_original",
            lambda valores: ", ".join(sorted(set(valores))),
        ),
    )
    .reset_index()
)

nomes_repetidos = nomes_repetidos[
    nomes_repetidos["quantidade"] > 1
]

print("Quantidade de nomes de arquivos repetidos:")
print(len(nomes_repetidos))

nomes_repetidos.head(20)

Quantidade de nomes de arquivos repetidos:
0

Empty DataFrame
Columns: [nome_arquivo, quantidade, classes, divisoes]
Index: []

In [13]:
arquivos_invalidos = []

for indice, caminho in enumerate(inventario["caminho"], start=1):
    try:
        with Image.open(caminho) as imagem:
            imagem.verify()

    except Exception as erro:
        arquivos_invalidos.append(
            {
                "caminho": caminho,
                "erro": str(erro),
            }
        )

    if indice % 1000 == 0:
        print(f"{indice} imagens verificadas...")

print("\nVerificação concluída.")
print("Quantidade de arquivos inválidos:")
print(len(arquivos_invalidos))

1000 imagens verificadas...
2000 imagens verificadas...
3000 imagens verificadas...
4000 imagens verificadas...
5000 imagens verificadas...

Verificação concluída.
Quantidade de arquivos inválidos:
0

In [14]:
caminho_inventario = Path(
    "/kaggle/working/inventario_imagens.csv"
)

inventario.to_csv(
    caminho_inventario,
    index=False,
    encoding="utf-8",
)

print("Inventário salvo em:")
print(caminho_inventario)

print("\nO arquivo foi criado?")
print(caminho_inventario.exists())

Inventário salvo em:
/kaggle/working/inventario_imagens.csv

O arquivo foi criado?
True

In [15]:
print("Tipo do inventário:")
print(type(inventario))

print("\nQuantidade de linhas:")
print(len(inventario))

Tipo do inventário:
<class 'pandas.core.frame.DataFrame'>

Quantidade de linhas:
5856

In [16]:
import hashlib
import re
from pathlib import Path

import pandas as pd

In [17]:
print("Tamanho do inventário:", inventario.shape)

print("\nColunas do inventário:")
print(inventario.columns.tolist())

Tamanho do inventário: (5856, 5)

Colunas do inventário:
['caminho', 'nome_arquivo', 'divisao_original', 'classe', 'extensao']

In [18]:
for classe in ["NORMAL", "PNEUMONIA"]:
    print(f"\n===== {classe} =====")

    amostra = (
        inventario[inventario["classe"] == classe]
        [["nome_arquivo", "divisao_original"]]
        .sample(n=15, random_state=42)
    )

    print(amostra.to_string(index=False))

===== NORMAL =====
                  nome_arquivo divisao_original
     NORMAL2-IM-0995-0001.jpeg            train
             IM-0503-0001.jpeg            train
     NORMAL2-IM-1431-0001.jpeg              val
             IM-0095-0001.jpeg             test
     NORMAL2-IM-0489-0001.jpeg            train
     NORMAL2-IM-0316-0001.jpeg             test
     NORMAL2-IM-0476-0001.jpeg            train
             IM-0476-0001.jpeg            train
             IM-0654-0001.jpeg            train
             IM-0227-0001.jpeg            train
             IM-0604-0001.jpeg            train
NORMAL2-IM-1258-0001-0001.jpeg            train
             IM-0542-0001.jpeg            train
     NORMAL2-IM-1035-0001.jpeg            train
     NORMAL2-IM-1058-0001.jpeg            train

===== PNEUMONIA =====
                 nome_arquivo divisao_original
person1689_bacteria_4473.jpeg            train
person1538_bacteria_4021.jpeg            train
   person1164_virus_1957.jpeg            train
person1615_bacteria_4249.jpeg            train
 person531_bacteria_2239.jpeg            train
    person807_virus_1441.jpeg            train
person1764_bacteria_4607.jpeg            train
 person423_bacteria_1854.jpeg            train
     person395_virus_788.jpeg            train
person1470_bacteria_3829.jpeg            train
     person115_virus_219.jpeg            train
    person707_virus_1305.jpeg            train
     person124_virus_233.jpeg            train
       person37_virus_82.jpeg             test
   person88_bacteria_437.jpeg             test

In [19]:
import re

In [20]:
pneumonia = inventario[inventario["classe"] == "PNEUMONIA"].copy()

print("Quantidade de imagens PNEUMONIA:", len(pneumonia))

Quantidade de imagens PNEUMONIA: 4273

In [21]:
padrao_pneumonia = r"^person\d+_(bacteria|virus)_\d+\.jpeg$"

pneumonia["padrao_esperado"] = pneumonia["nome_arquivo"].str.match(
    padrao_pneumonia
)

print(pneumonia["padrao_esperado"].value_counts())

padrao_esperado
True     4272
False       1
Name: count, dtype: int64

In [22]:
excecoes_pneumonia = pneumonia[
    ~pneumonia["padrao_esperado"]
]

print(
    excecoes_pneumonia[
        ["nome_arquivo", "divisao_original", "caminho"]
    ].to_string(index=False)
)

              nome_arquivo divisao_original                                                                                                             caminho
person447_virus_921_1.jpeg            train /kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/train/PNEUMONIA/person447_virus_921_1.jpeg

In [23]:
arquivos_person447 = pneumonia[
    pneumonia["nome_arquivo"].str.startswith("person447_")
]

print(
    arquivos_person447[
        ["nome_arquivo", "divisao_original"]
    ]
    .sort_values("nome_arquivo")
    .to_string(index=False)
)

                nome_arquivo divisao_original
person447_bacteria_1932.jpeg            train
    person447_virus_921.jpeg            train
  person447_virus_921_1.jpeg            train

In [24]:
pneumonia["id_candidato"] = pneumonia["nome_arquivo"].str.extract(
    r"^(person\d+)"
)

print(
    pneumonia[
        ["nome_arquivo", "id_candidato"]
    ].head(10).to_string(index=False)
)

                 nome_arquivo id_candidato
person1000_bacteria_2931.jpeg   person1000
   person1000_virus_1681.jpeg   person1000
person1001_bacteria_2932.jpeg   person1001
person1002_bacteria_2933.jpeg   person1002
person1003_bacteria_2934.jpeg   person1003
   person1003_virus_1685.jpeg   person1003
person1004_bacteria_2935.jpeg   person1004
   person1004_virus_1686.jpeg   person1004
person1005_bacteria_2936.jpeg   person1005
   person1005_virus_1688.jpeg   person1005

In [25]:
quantidade_sem_id = pneumonia["id_candidato"].isna().sum()

print("Imagens PNEUMONIA sem identificador candidato:", quantidade_sem_id)

Imagens PNEUMONIA sem identificador candidato: 0

In [26]:
quantidade_ids = pneumonia["id_candidato"].nunique()

print("Quantidade de imagens PNEUMONIA:", len(pneumonia))
print("Quantidade de identificadores candidatos:", quantidade_ids)

Quantidade de imagens PNEUMONIA: 4273
Quantidade de identificadores candidatos: 1674

In [27]:
imagens_por_id = pneumonia["id_candidato"].value_counts()

print(imagens_por_id.head(10))

id_candidato
person23      31
person124     20
person441     18
person30      15
person1320    14
person348     13
person326     12
person281     12
person26      12
person1411    12
Name: count, dtype: int64

In [28]:
ids_com_multiplas_imagens = (imagens_por_id > 1).sum()

print(
    "Identificadores candidatos com mais de uma imagem:",
    ids_com_multiplas_imagens
)

Identificadores candidatos com mais de uma imagem: 1110

In [29]:
maior_quantidade = imagens_por_id.max()
id_maior_grupo = imagens_por_id.idxmax()

print("Maior número de imagens para um mesmo ID:", maior_quantidade)
print("ID candidato com mais imagens:", id_maior_grupo)

Maior número de imagens para um mesmo ID: 31
ID candidato com mais imagens: person23

In [30]:
divisoes_por_id = (
    pneumonia
    .groupby("id_candidato")["divisao_original"]
    .nunique()
)

print(divisoes_por_id.value_counts().sort_index())

divisao_original
1    1504
2     170
Name: count, dtype: int64

In [31]:
ids_entre_divisoes = divisoes_por_id[
    divisoes_por_id > 1
]

print(
    "Identificadores candidatos presentes em mais de uma divisão:",
    len(ids_entre_divisoes)
)

Identificadores candidatos presentes em mais de uma divisão: 170

In [32]:
lista_divisoes_por_id = (
    pneumonia
    .groupby("id_candidato")["divisao_original"]
    .agg(lambda x: sorted(x.unique()))
)

print(lista_divisoes_por_id.head(10))

id_candidato
person1       [test, train]
person10      [test, train]
person100     [test, train]
person1000          [train]
person1001          [train]
person1002          [train]
person1003          [train]
person1004          [train]
person1005          [train]
person1006          [train]
Name: divisao_original, dtype: object

In [33]:
sobreposicoes = lista_divisoes_por_id[
    lista_divisoes_por_id.apply(len) > 1
]

print("Quantidade de IDs com sobreposição:", len(sobreposicoes))
print(sobreposicoes.head(20))

Quantidade de IDs com sobreposição: 170
id_candidato
person1      [test, train]
person10     [test, train]
person100    [test, train]
person101    [test, train]
person102    [test, train]
person103    [test, train]
person104    [test, train]
person108    [test, train]
person109    [test, train]
person11     [test, train]
person110    [test, train]
person111    [test, train]
person112    [test, train]
person113    [test, train]
person114    [test, train]
person117    [test, train]
person118    [test, train]
person119    [test, train]
person120    [test, train]
person122    [test, train]
Name: divisao_original, dtype: object

In [34]:
combinacoes_divisoes = (
    sobreposicoes
    .apply(lambda x: " + ".join(x))
    .value_counts()
)

print(combinacoes_divisoes)

divisao_original
test + train    170
Name: count, dtype: int64

In [35]:
ids_exemplo = sobreposicoes.index[:5].tolist()

print("IDs escolhidos para inspeção:")
print(ids_exemplo)

IDs escolhidos para inspeção:
['person1', 'person10', 'person100', 'person101', 'person102']

In [36]:
exemplos_sobreposicao = pneumonia[
    pneumonia["id_candidato"].isin(ids_exemplo)
][
    ["id_candidato", "nome_arquivo", "divisao_original"]
].sort_values(
    ["id_candidato", "divisao_original", "nome_arquivo"]
)

print(exemplos_sobreposicao.to_string(index=False))

id_candidato                nome_arquivo divisao_original
     person1       person1_virus_11.jpeg             test
     person1       person1_virus_12.jpeg             test
     person1       person1_virus_13.jpeg             test
     person1        person1_virus_6.jpeg             test
     person1        person1_virus_7.jpeg             test
     person1        person1_virus_8.jpeg             test
     person1        person1_virus_9.jpeg             test
     person1     person1_bacteria_1.jpeg            train
     person1     person1_bacteria_2.jpeg            train
    person10      person10_virus_35.jpeg             test
    person10   person10_bacteria_43.jpeg            train
   person100 person100_bacteria_475.jpeg             test
   person100 person100_bacteria_477.jpeg             test
   person100 person100_bacteria_478.jpeg             test
   person100 person100_bacteria_479.jpeg             test
   person100 person100_bacteria_480.jpeg             test
   person100 person100_bacteria_481.jpeg             test
   person100 person100_bacteria_482.jpeg             test
   person100    person100_virus_184.jpeg            train
   person101 person101_bacteria_483.jpeg             test
   person101 person101_bacteria_484.jpeg             test
   person101 person101_bacteria_485.jpeg             test
   person101 person101_bacteria_486.jpeg             test
   person101    person101_virus_187.jpeg            train
   person101    person101_virus_188.jpeg            train
   person102 person102_bacteria_487.jpeg             test
   person102    person102_virus_189.jpeg            train

In [37]:
pneumonia["subtipo_nome"] = pneumonia["nome_arquivo"].str.extract(
    r"_(bacteria|virus)_"
)

print(
    pneumonia[
        ["nome_arquivo", "id_candidato", "subtipo_nome"]
    ].head(10).to_string(index=False)
)

                 nome_arquivo id_candidato subtipo_nome
person1000_bacteria_2931.jpeg   person1000     bacteria
   person1000_virus_1681.jpeg   person1000        virus
person1001_bacteria_2932.jpeg   person1001     bacteria
person1002_bacteria_2933.jpeg   person1002     bacteria
person1003_bacteria_2934.jpeg   person1003     bacteria
   person1003_virus_1685.jpeg   person1003        virus
person1004_bacteria_2935.jpeg   person1004     bacteria
   person1004_virus_1686.jpeg   person1004        virus
person1005_bacteria_2936.jpeg   person1005     bacteria
   person1005_virus_1688.jpeg   person1005        virus

In [38]:
print(
    "Imagens sem subtipo identificado:",
    pneumonia["subtipo_nome"].isna().sum()
)

print("\nQuantidade por subtipo:")
print(pneumonia["subtipo_nome"].value_counts())

Imagens sem subtipo identificado: 0

Quantidade por subtipo:
subtipo_nome
bacteria    2780
virus       1493
Name: count, dtype: int64

In [39]:
subtipos_por_id = (
    pneumonia
    .groupby("id_candidato")["subtipo_nome"]
    .nunique()
)

print(subtipos_por_id.value_counts().sort_index())

subtipo_nome
1    695
2    979
Name: count, dtype: int64

In [40]:
ids_sobrepostos = sobreposicoes.index

dados_sobrepostos = pneumonia[
    pneumonia["id_candidato"].isin(ids_sobrepostos)
]

subtipos_nos_sobrepostos = (
    dados_sobrepostos
    .groupby("id_candidato")["subtipo_nome"]
    .nunique()
)

print(
    "Dos 170 IDs entre train e test:"
)

print(subtipos_nos_sobrepostos.value_counts().sort_index())

Dos 170 IDs entre train e test:
subtipo_nome
2    170
Name: count, dtype: int64

In [41]:
pneumonia["id_grupo_candidato"] = (
    pneumonia["id_candidato"]
    + "_"
    + pneumonia["subtipo_nome"]
)

print(
    pneumonia[
        ["nome_arquivo", "id_grupo_candidato"]
    ].head(10).to_string(index=False)
)

                 nome_arquivo  id_grupo_candidato
person1000_bacteria_2931.jpeg person1000_bacteria
   person1000_virus_1681.jpeg    person1000_virus
person1001_bacteria_2932.jpeg person1001_bacteria
person1002_bacteria_2933.jpeg person1002_bacteria
person1003_bacteria_2934.jpeg person1003_bacteria
   person1003_virus_1685.jpeg    person1003_virus
person1004_bacteria_2935.jpeg person1004_bacteria
   person1004_virus_1686.jpeg    person1004_virus
person1005_bacteria_2936.jpeg person1005_bacteria
   person1005_virus_1688.jpeg    person1005_virus

In [42]:
quantidade_grupos = pneumonia["id_grupo_candidato"].nunique()

print("Quantidade de imagens PNEUMONIA:", len(pneumonia))
print("Quantidade de grupos candidatos:", quantidade_grupos)

Quantidade de imagens PNEUMONIA: 4273
Quantidade de grupos candidatos: 2653

In [43]:
divisoes_por_grupo = (
    pneumonia
    .groupby("id_grupo_candidato")["divisao_original"]
    .nunique()
)

print(divisoes_por_grupo.value_counts().sort_index())

divisao_original
1    2653
Name: count, dtype: int64

In [44]:
grupos_entre_divisoes = divisoes_por_grupo[
    divisoes_por_grupo > 1
]

print(
    "Grupos candidatos presentes em mais de uma divisão:",
    len(grupos_entre_divisoes)
)

Grupos candidatos presentes em mais de uma divisão: 0

In [45]:
normal = inventario[
    inventario["classe"] == "NORMAL"
].copy()

print("Quantidade de imagens NORMAL:", len(normal))

Quantidade de imagens NORMAL: 1583

In [46]:
normal["formato_nome"] = (
    normal["nome_arquivo"]
    .str.replace(r"\d+", "N", regex=True)
)

print(
    normal[
        ["nome_arquivo", "formato_nome"]
    ].head(15).to_string(index=False)
)

     nome_arquivo formato_nome
IM-0115-0001.jpeg  IM-N-N.jpeg
IM-0117-0001.jpeg  IM-N-N.jpeg
IM-0119-0001.jpeg  IM-N-N.jpeg
IM-0122-0001.jpeg  IM-N-N.jpeg
IM-0125-0001.jpeg  IM-N-N.jpeg
IM-0127-0001.jpeg  IM-N-N.jpeg
IM-0128-0001.jpeg  IM-N-N.jpeg
IM-0129-0001.jpeg  IM-N-N.jpeg
IM-0131-0001.jpeg  IM-N-N.jpeg
IM-0133-0001.jpeg  IM-N-N.jpeg
IM-0135-0001.jpeg  IM-N-N.jpeg
IM-0137-0001.jpeg  IM-N-N.jpeg
IM-0140-0001.jpeg  IM-N-N.jpeg
IM-0141-0001.jpeg  IM-N-N.jpeg
IM-0143-0001.jpeg  IM-N-N.jpeg

In [47]:
contagem_formatos_normal = normal["formato_nome"].value_counts()

print(contagem_formatos_normal)

formato_nome
NORMALN-IM-N-N.jpeg      858
IM-N-N.jpeg              582
IM-N-N-N.jpeg             84
NORMALN-IM-N-N-N.jpeg     59
Name: count, dtype: int64

In [48]:
for formato in contagem_formatos_normal.index:

    print(f"\n===== {formato} =====")

    exemplos = normal[
        normal["formato_nome"] == formato
    ][
        ["nome_arquivo", "divisao_original"]
    ].head(10)

    print(exemplos.to_string(index=False))

===== NORMALN-IM-N-N.jpeg =====
             nome_arquivo divisao_original
NORMAL2-IM-0383-0001.jpeg            train
NORMAL2-IM-0384-0001.jpeg            train
NORMAL2-IM-0385-0001.jpeg            train
NORMAL2-IM-0386-0001.jpeg            train
NORMAL2-IM-0388-0001.jpeg            train
NORMAL2-IM-0389-0001.jpeg            train
NORMAL2-IM-0390-0001.jpeg            train
NORMAL2-IM-0391-0001.jpeg            train
NORMAL2-IM-0392-0001.jpeg            train
NORMAL2-IM-0393-0001.jpeg            train

===== IM-N-N.jpeg =====
     nome_arquivo divisao_original
IM-0115-0001.jpeg            train
IM-0117-0001.jpeg            train
IM-0119-0001.jpeg            train
IM-0122-0001.jpeg            train
IM-0125-0001.jpeg            train
IM-0127-0001.jpeg            train
IM-0128-0001.jpeg            train
IM-0129-0001.jpeg            train
IM-0131-0001.jpeg            train
IM-0133-0001.jpeg            train

===== IM-N-N-N.jpeg =====
          nome_arquivo divisao_original
IM-0429-0001-0001.jpeg            train
IM-0429-0001-0002.jpeg            train
IM-0435-0001-0001.jpeg            train
IM-0437-0001-0001.jpeg            train
IM-0437-0001-0002.jpeg            train
IM-0439-0001-0001.jpeg            train
IM-0439-0001-0002.jpeg            train
IM-0453-0001-0002.jpeg            train
IM-0467-0001-0001.jpeg            train
IM-0467-0001-0002.jpeg            train

===== NORMALN-IM-N-N-N.jpeg =====
                  nome_arquivo divisao_original
NORMAL2-IM-0395-0001-0001.jpeg            train
NORMAL2-IM-0395-0001-0002.jpeg            train
NORMAL2-IM-0416-0001-0001.jpeg            train
NORMAL2-IM-0416-0001-0002.jpeg            train
NORMAL2-IM-0535-0001-0002.jpeg            train
NORMAL2-IM-0555-0001-0001.jpeg            train
NORMAL2-IM-0555-0001-0002.jpeg            train
NORMAL2-IM-0587-0001-0001.jpeg            train
NORMAL2-IM-0587-0001-0002.jpeg            train
NORMAL2-IM-0684-0001-0001.jpeg            train

In [49]:
formatos_por_divisao = (
    normal
    .groupby(
        ["formato_nome", "divisao_original"]
    )
    .size()
    .unstack(fill_value=0)
)

print(formatos_por_divisao)

divisao_original       test  train  val
formato_nome
IM-N-N-N.jpeg             4     80    0
IM-N-N.jpeg              65    517    0
NORMALN-IM-N-N-N.jpeg     6     53    0
NORMALN-IM-N-N.jpeg     159    691    8

In [50]:
normal["id_grupo_candidato"] = normal["nome_arquivo"].str.extract(
    r"^((?:NORMAL2-)?IM-\d+)"
)

print(
    normal[
        ["nome_arquivo", "id_grupo_candidato"]
    ].head(15).to_string(index=False)
)

     nome_arquivo id_grupo_candidato
IM-0115-0001.jpeg            IM-0115
IM-0117-0001.jpeg            IM-0117
IM-0119-0001.jpeg            IM-0119
IM-0122-0001.jpeg            IM-0122
IM-0125-0001.jpeg            IM-0125
IM-0127-0001.jpeg            IM-0127
IM-0128-0001.jpeg            IM-0128
IM-0129-0001.jpeg            IM-0129
IM-0131-0001.jpeg            IM-0131
IM-0133-0001.jpeg            IM-0133
IM-0135-0001.jpeg            IM-0135
IM-0137-0001.jpeg            IM-0137
IM-0140-0001.jpeg            IM-0140
IM-0141-0001.jpeg            IM-0141
IM-0143-0001.jpeg            IM-0143

In [51]:
sem_grupo_normal = normal["id_grupo_candidato"].isna().sum()

print(
    "Imagens NORMAL sem identificador de grupo candidato:",
    sem_grupo_normal
)

Imagens NORMAL sem identificador de grupo candidato: 0

In [52]:
quantidade_grupos_normal = normal["id_grupo_candidato"].nunique()

print("Quantidade de imagens NORMAL:", len(normal))
print(
    "Quantidade de grupos candidatos NORMAL:",
    quantidade_grupos_normal
)

Quantidade de imagens NORMAL: 1583
Quantidade de grupos candidatos NORMAL: 1444

In [53]:
imagens_por_grupo_normal = (
    normal["id_grupo_candidato"]
    .value_counts()
)

print(imagens_por_grupo_normal.head(15))

id_grupo_candidato
IM-0553            4
IM-0523            4
IM-0629            4
NORMAL2-IM-1128    3
IM-0519            3
NORMAL2-IM-0246    3
IM-0525            3
NORMAL2-IM-1294    3
NORMAL2-IM-1142    3
NORMAL2-IM-0587    3
IM-0533            3
NORMAL2-IM-0851    3
NORMAL2-IM-1266    3
IM-0539            3
NORMAL2-IM-1154    3
Name: count, dtype: int64

In [54]:
grupos_normal_multiplas = (
    imagens_por_grupo_normal > 1
).sum()

print(
    "Grupos candidatos NORMAL com mais de uma imagem:",
    grupos_normal_multiplas
)

print(
    "Maior número de imagens em um mesmo grupo:",
    imagens_por_grupo_normal.max()
)

Grupos candidatos NORMAL com mais de uma imagem: 75
Maior número de imagens em um mesmo grupo: 4

In [55]:
divisoes_por_grupo_normal = (
    normal
    .groupby("id_grupo_candidato")["divisao_original"]
    .nunique()
)

print(
    divisoes_por_grupo_normal
    .value_counts()
    .sort_index()
)

divisao_original
1    1444
Name: count, dtype: int64

In [56]:
grupos_normal_entre_divisoes = divisoes_por_grupo_normal[
    divisoes_por_grupo_normal > 1
]

print(
    "Grupos candidatos NORMAL presentes em mais de uma divisão:",
    len(grupos_normal_entre_divisoes)
)

Grupos candidatos NORMAL presentes em mais de uma divisão: 0

In [57]:
import hashlib

In [58]:
def calcular_sha256(caminho_arquivo):
    sha256 = hashlib.sha256()

    with open(caminho_arquivo, "rb") as arquivo:
        for bloco in iter(lambda: arquivo.read(8192), b""):
            sha256.update(bloco)

    return sha256.hexdigest()

In [59]:
imagem_teste = inventario.iloc[0]

print("Arquivo de teste:")
print(imagem_teste["nome_arquivo"])

print("\nCaminho:")
print(imagem_teste["caminho"])

Arquivo de teste:
IM-0115-0001.jpeg

Caminho:
/kaggle/input/datasets/paultimothymooney/chest-xray-pneumonia/chest_xray/train/NORMAL/IM-0115-0001.jpeg

In [60]:
hash_teste = calcular_sha256(
    imagem_teste["caminho"]
)

print("SHA-256:")
print(hash_teste)

SHA-256:
de2079fb45d4bb0e4c6a48481e7b6ee31ab7601e83b43cd07820168b93de1d13

In [61]:
print(
    "Quantidade de caracteres do hash:",
    len(hash_teste)
)

Quantidade de caracteres do hash: 64

In [62]:
inventario_auditado = inventario.copy()

print("Tamanho do inventário auditado:", inventario_auditado.shape)
print("Colunas atuais:", inventario_auditado.columns.tolist())

Tamanho do inventário auditado: (5856, 5)
Colunas atuais: ['caminho', 'nome_arquivo', 'divisao_original', 'classe', 'extensao']

In [63]:
inventario_auditado["sha256"] = (
    inventario_auditado["caminho"]
    .apply(calcular_sha256)
)

In [64]:
print("Tamanho:", inventario_auditado.shape)

print("\nColunas:")
print(inventario_auditado.columns.tolist())

print("\nPrimeiros hashes:")
print(
    inventario_auditado[
        ["nome_arquivo", "sha256"]
    ].head()
)

Tamanho: (5856, 6)

Colunas:
['caminho', 'nome_arquivo', 'divisao_original', 'classe', 'extensao', 'sha256']

Primeiros hashes:
        nome_arquivo                                             sha256
0  IM-0115-0001.jpeg  de2079fb45d4bb0e4c6a48481e7b6ee31ab7601e83b43c...
1  IM-0117-0001.jpeg  05bc425eda168493cbe38eea4c079edbbfad1e17e34778...
2  IM-0119-0001.jpeg  46c9ea6d3c6ef09eac134e3cb3294caaa63aa2b8c53278...
3  IM-0122-0001.jpeg  eea992f8a396289babd7fc152293c35bce98fc2d009925...
4  IM-0125-0001.jpeg  22c9ea7cc8b235db38e9dfb16b6c682885dba83dfd7553...

In [65]:
print(
    "Hashes ausentes:",
    inventario_auditado["sha256"].isna().sum()
)

print("\nTamanho dos hashes:")
print(
    inventario_auditado["sha256"]
    .str.len()
    .value_counts()
)

Hashes ausentes: 0

Tamanho dos hashes:
sha256
64    5856
Name: count, dtype: int64

In [66]:
quantidade_hashes_unicos = inventario_auditado["sha256"].nunique()

contagem_por_hash = inventario_auditado["sha256"].value_counts()

grupos_hash_repetido = (
    contagem_por_hash > 1
).sum()

arquivos_em_duplicatas = (
    inventario_auditado["sha256"]
    .duplicated(keep=False)
    .sum()
)

copias_excedentes = (
    len(inventario_auditado) - quantidade_hashes_unicos
)

print("Total de arquivos:", len(inventario_auditado))
print("Hashes únicos:", quantidade_hashes_unicos)
print("Grupos de hashes repetidos:", grupos_hash_repetido)
print("Arquivos envolvidos em duplicatas:", arquivos_em_duplicatas)
print("Cópias excedentes:", copias_excedentes)

Total de arquivos: 5856
Hashes únicos: 5824
Grupos de hashes repetidos: 30
Arquivos envolvidos em duplicatas: 62
Cópias excedentes: 32

In [67]:
contagem_hashes_repetidos = contagem_por_hash[
    contagem_por_hash > 1
]

print("Quantidade de grupos duplicados:", len(contagem_hashes_repetidos))

print("\nDistribuição do tamanho dos grupos:")
print(
    contagem_hashes_repetidos
    .value_counts()
    .sort_index()
)

print(
    "\nMaior número de ocorrências do mesmo conteúdo:",
    contagem_hashes_repetidos.max()
)

Quantidade de grupos duplicados: 30

Distribuição do tamanho dos grupos:
count
2    28
3     2
Name: count, dtype: int64

Maior número de ocorrências do mesmo conteúdo: 3

In [68]:
duplicatas_exatas = inventario_auditado[
    inventario_auditado["sha256"].isin(
        contagem_hashes_repetidos.index
    )
].copy()

print("Quantidade de arquivos duplicados:", len(duplicatas_exatas))

print("\nTamanho do DataFrame:")
print(duplicatas_exatas.shape)

Quantidade de arquivos duplicados: 62

Tamanho do DataFrame:
(62, 6)

In [69]:
resumo_duplicatas = (
    duplicatas_exatas
    .groupby("sha256")
    .agg(
        quantidade_arquivos=("sha256", "size"),
        quantidade_divisoes=("divisao_original", "nunique"),
        quantidade_classes=("classe", "nunique")
    )
)

print("Distribuição por quantidade de divisões:")
print(
    resumo_duplicatas["quantidade_divisoes"]
    .value_counts()
    .sort_index()
)

print("\nDistribuição por quantidade de classes:")
print(
    resumo_duplicatas["quantidade_classes"]
    .value_counts()
    .sort_index()
)

Distribuição por quantidade de divisões:
quantidade_divisoes
1    30
Name: count, dtype: int64

Distribuição por quantidade de classes:
quantidade_classes
1    30
Name: count, dtype: int64

In [70]:
resumo_duplicatas["divisao"] = (
    duplicatas_exatas
    .groupby("sha256")["divisao_original"]
    .first()
)

resumo_duplicatas["classe"] = (
    duplicatas_exatas
    .groupby("sha256")["classe"]
    .first()
)

print(resumo_duplicatas.head())

                                                    quantidade_arquivos  \
sha256
0033d6b3f444134e4d3a320b4c9e34cdbc4ffe1fdb90023...                    2
1679da3844455b96ea5e792b12d24a832c4dba570628c27...                    2
1e273d0058cfb3cf5fb401b74797903a3e66c75fd2dbd8d...                    2
3853a4552e0bc9aea1f45b2e7ee27be5954cdf9a0365d79...                    2
409f0f6c0f8a5b8ed4e0645633b07812aff5991aaee75bb...                    2

                                                    quantidade_divisoes  \
sha256
0033d6b3f444134e4d3a320b4c9e34cdbc4ffe1fdb90023...                    1
1679da3844455b96ea5e792b12d24a832c4dba570628c27...                    1
1e273d0058cfb3cf5fb401b74797903a3e66c75fd2dbd8d...                    1
3853a4552e0bc9aea1f45b2e7ee27be5954cdf9a0365d79...                    1
409f0f6c0f8a5b8ed4e0645633b07812aff5991aaee75bb...                    1

                                                    quantidade_classes  \
sha256
0033d6b3f444134e4d3a320b4c9e34cdbc4ffe1fdb90023...                   1
1679da3844455b96ea5e792b12d24a832c4dba570628c27...                   1
1e273d0058cfb3cf5fb401b74797903a3e66c75fd2dbd8d...                   1
3853a4552e0bc9aea1f45b2e7ee27be5954cdf9a0365d79...                   1
409f0f6c0f8a5b8ed4e0645633b07812aff5991aaee75bb...                   1

                                                   divisao     classe
sha256
0033d6b3f444134e4d3a320b4c9e34cdbc4ffe1fdb90023...   train  PNEUMONIA
1679da3844455b96ea5e792b12d24a832c4dba570628c27...   train  PNEUMONIA
1e273d0058cfb3cf5fb401b74797903a3e66c75fd2dbd8d...   train  PNEUMONIA
3853a4552e0bc9aea1f45b2e7ee27be5954cdf9a0365d79...   train     NORMAL
409f0f6c0f8a5b8ed4e0645633b07812aff5991aaee75bb...    test     NORMAL

In [71]:
grupos_por_classe_divisao = (
    resumo_duplicatas
    .groupby(["classe", "divisao"])
    .size()
)

print(grupos_por_classe_divisao)

classe     divisao
NORMAL     test        3
           train       1
PNEUMONIA  test        3
           train      23
dtype: int64

In [72]:
arquivos_duplicados_por_classe_divisao = (
    duplicatas_exatas
    .groupby(["classe", "divisao_original"])
    .size()
)

print(arquivos_duplicados_por_classe_divisao)

classe     divisao_original
NORMAL     test                 6
           train                2
PNEUMONIA  test                 6
           train               48
dtype: int64

In [73]:
exemplos_duplicatas = (
    duplicatas_exatas[
        ["sha256", "nome_arquivo", "classe", "divisao_original"]
    ]
    .sort_values(
        ["sha256", "nome_arquivo"]
    )
)

print(exemplos_duplicatas.head(20).to_string(index=False))

                                                          sha256                   nome_arquivo    classe divisao_original
0033d6b3f444134e4d3a320b4c9e34cdbc4ffe1fdb90023673ed1df46c643314     person1159_virus_1944.jpeg PNEUMONIA            train
0033d6b3f444134e4d3a320b4c9e34cdbc4ffe1fdb90023673ed1df46c643314     person1159_virus_1945.jpeg PNEUMONIA            train
1679da3844455b96ea5e792b12d24a832c4dba570628c27cb594fbfd7e2c9914       person124_virus_246.jpeg PNEUMONIA            train
1679da3844455b96ea5e792b12d24a832c4dba570628c27cb594fbfd7e2c9914       person124_virus_247.jpeg PNEUMONIA            train
1e273d0058cfb3cf5fb401b74797903a3e66c75fd2dbd8d14f4ef0890013d7c4     person1261_virus_2147.jpeg PNEUMONIA            train
1e273d0058cfb3cf5fb401b74797903a3e66c75fd2dbd8d14f4ef0890013d7c4     person1261_virus_2148.jpeg PNEUMONIA            train
3853a4552e0bc9aea1f45b2e7ee27be5954cdf9a0365d7972663b62b5495d9ae NORMAL2-IM-0587-0001-0001.jpeg    NORMAL            train
3853a4552e0bc9aea1f45b2e7ee27be5954cdf9a0365d7972663b62b5495d9ae NORMAL2-IM-0587-0001-0002.jpeg    NORMAL            train
409f0f6c0f8a5b8ed4e0645633b07812aff5991aaee75bbe48044711a55c7c2c NORMAL2-IM-0173-0001-0001.jpeg    NORMAL             test
409f0f6c0f8a5b8ed4e0645633b07812aff5991aaee75bbe48044711a55c7c2c NORMAL2-IM-0173-0001-0002.jpeg    NORMAL             test
4d9f500ccfdde23bd7deb003994aeaf41537834458287bea61e9e80e78e8b091  person1481_bacteria_3866.jpeg PNEUMONIA            train
4d9f500ccfdde23bd7deb003994aeaf41537834458287bea61e9e80e78e8b091  person1481_bacteria_3867.jpeg PNEUMONIA            train
4e4df8461fc3412959b5c34abb54977332738400aeab75689b2c33ef00e27f99  person1496_bacteria_3909.jpeg PNEUMONIA            train
4e4df8461fc3412959b5c34abb54977332738400aeab75689b2c33ef00e27f99  person1496_bacteria_3910.jpeg PNEUMONIA            train
514afd0fa610117fbfef0e6e5b81a4d73a24815827594119af684fb8d0b2f8e2     person1661_virus_2872.jpeg PNEUMONIA             test
514afd0fa610117fbfef0e6e5b81a4d73a24815827594119af684fb8d0b2f8e2     person1661_virus_2873.jpeg PNEUMONIA             test
5824d55942d95216b7808fafa10db02aeaf63485a1a4f480faa951794a2d28b3    person128_bacteria_606.jpeg PNEUMONIA             test
5824d55942d95216b7808fafa10db02aeaf63485a1a4f480faa951794a2d28b3    person128_bacteria_607.jpeg PNEUMONIA             test
704f62a1b29b3ae0ef1995610cc7cd63d9f0393bb5b653ded033cbcd1c92d409  person1628_bacteria_4297.jpeg PNEUMONIA            train
704f62a1b29b3ae0ef1995610cc7cd63d9f0393bb5b653ded033cbcd1c92d409  person1628_bacteria_4298.jpeg PNEUMONIA            train

In [74]:
inventario_auditado["grupo_candidato"] = None

print(inventario_auditado.columns.tolist())

['caminho', 'nome_arquivo', 'divisao_original', 'classe', 'extensao', 'sha256', 'grupo_candidato']

In [75]:
mascara_pneumonia = (
    inventario_auditado["classe"] == "PNEUMONIA"
)

inventario_auditado.loc[
    mascara_pneumonia,
    "grupo_candidato"
] = (
    inventario_auditado.loc[
        mascara_pneumonia,
        "nome_arquivo"
    ]
    .str.extract(
        r"^(person\d+_(?:bacteria|virus))",
        expand=False
    )
)

In [76]:
mascara_normal = (
    inventario_auditado["classe"] == "NORMAL"
)

inventario_auditado.loc[
    mascara_normal,
    "grupo_candidato"
] = (
    inventario_auditado.loc[
        mascara_normal,
        "nome_arquivo"
    ]
    .str.extract(
        r"^((?:NORMAL2-)?IM-\d+)",
        expand=False
    )
)

In [77]:
print(
    "Imagens sem grupo candidato:",
    inventario_auditado["grupo_candidato"].isna().sum()
)

print("\nExemplos:")
print(
    inventario_auditado[
        ["nome_arquivo", "classe", "grupo_candidato"]
    ].sample(
        n=10,
        random_state=42
    ).to_string(index=False)
)

Imagens sem grupo candidato: 0

Exemplos:
                 nome_arquivo    classe     grupo_candidato
 person398_bacteria_1799.jpeg PNEUMONIA  person398_bacteria
    person539_virus_1069.jpeg PNEUMONIA     person539_virus
    NORMAL2-IM-0908-0001.jpeg    NORMAL     NORMAL2-IM-0908
            IM-0160-0001.jpeg    NORMAL             IM-0160
    NORMAL2-IM-0666-0001.jpeg    NORMAL     NORMAL2-IM-0666
person1176_bacteria_3123.jpeg PNEUMONIA person1176_bacteria
    NORMAL2-IM-1175-0001.jpeg    NORMAL     NORMAL2-IM-1175
person1574_bacteria_4118.jpeg PNEUMONIA person1574_bacteria
   person56_bacteria_268.jpeg PNEUMONIA   person56_bacteria
   person1288_virus_2211.jpeg PNEUMONIA    person1288_virus

In [78]:
duplicatas_com_grupo = inventario_auditado[
    inventario_auditado["sha256"].isin(
        contagem_hashes_repetidos.index
    )
]

grupos_candidatos_por_hash = (
    duplicatas_com_grupo
    .groupby("sha256")["grupo_candidato"]
    .nunique()
)

print(
    "Distribuição da quantidade de grupos candidatos por hash:"
)

print(
    grupos_candidatos_por_hash
    .value_counts()
    .sort_index()
)

Distribuição da quantidade de grupos candidatos por hash:
grupo_candidato
1    29
2     1
Name: count, dtype: int64

In [79]:
hashes_com_multiplos_grupos = grupos_candidatos_por_hash[
    grupos_candidatos_por_hash > 1
]

print(
    "Quantidade de hashes associados a mais de um grupo candidato:",
    len(hashes_com_multiplos_grupos)
)

print(hashes_com_multiplos_grupos)

Quantidade de hashes associados a mais de um grupo candidato: 1
sha256
fae2085830a4c703c36348b3ccc2a5ddfd741c86f12dbef48d4a8a31726ae773    2
Name: grupo_candidato, dtype: int64

In [80]:
hash_problematico = hashes_com_multiplos_grupos.index[0]

caso_problematico = inventario_auditado[
    inventario_auditado["sha256"] == hash_problematico
][
    [
        "nome_arquivo",
        "classe",
        "divisao_original",
        "grupo_candidato",
        "sha256"
    ]
]

print(caso_problematico.to_string(index=False))

             nome_arquivo classe divisao_original grupo_candidato                                                           sha256
NORMAL2-IM-0095-0001.jpeg NORMAL             test NORMAL2-IM-0095 fae2085830a4c703c36348b3ccc2a5ddfd741c86f12dbef48d4a8a31726ae773
NORMAL2-IM-0096-0001.jpeg NORMAL             test NORMAL2-IM-0096 fae2085830a4c703c36348b3ccc2a5ddfd741c86f12dbef48d4a8a31726ae773

In [81]:
inventario_auditado["duplicata_exata"] = (
    inventario_auditado["sha256"]
    .duplicated(keep=False)
)

print(
    inventario_auditado["duplicata_exata"]
    .value_counts()
)

duplicata_exata
False    5794
True       62
Name: count, dtype: int64

In [82]:
ordem_duplicatas = (
    inventario_auditado
    .sort_values(
        ["sha256", "nome_arquivo"]
    )
)

indices_excedentes = (
    ordem_duplicatas[
        ordem_duplicatas["sha256"].duplicated(keep="first")
    ]
    .index
)

print(
    "Quantidade de cópias excedentes identificadas:",
    len(indices_excedentes)
)

Quantidade de cópias excedentes identificadas: 32

In [83]:
inventario_auditado["copia_excedente"] = False

inventario_auditado.loc[
    indices_excedentes,
    "copia_excedente"
] = True

print(
    inventario_auditado["copia_excedente"]
    .value_counts()
)

copia_excedente
False    5824
True       32
Name: count, dtype: int64

In [84]:
verificacao_duplicatas = (
    inventario_auditado
    .groupby(
        ["duplicata_exata", "copia_excedente"]
    )
    .size()
)

print(verificacao_duplicatas)

duplicata_exata  copia_excedente
False            False              5794
True             False                30
                 True                 32
dtype: int64

In [85]:
print(
    inventario_auditado[
        inventario_auditado["sha256"] == hash_problematico
    ][
        [
            "nome_arquivo",
            "grupo_candidato",
            "duplicata_exata",
            "copia_excedente"
        ]
    ]
    .sort_values("nome_arquivo")
    .to_string(index=False)
)

             nome_arquivo grupo_candidato  duplicata_exata  copia_excedente
NORMAL2-IM-0095-0001.jpeg NORMAL2-IM-0095             True            False
NORMAL2-IM-0096-0001.jpeg NORMAL2-IM-0096             True             True

In [86]:
print("Tamanho final:", inventario_auditado.shape)

print("\nColunas finais:")
print(inventario_auditado.columns.tolist())

Tamanho final: (5856, 9)

Colunas finais:
['caminho', 'nome_arquivo', 'divisao_original', 'classe', 'extensao', 'sha256', 'grupo_candidato', 'duplicata_exata', 'copia_excedente']

In [87]:
caminho_inventario_auditado = (
    "/kaggle/working/inventario_imagens_auditado.csv"
)

inventario_auditado.to_csv(
    caminho_inventario_auditado,
    index=False
)

print("Arquivo salvo em:")
print(caminho_inventario_auditado)

Arquivo salvo em:
/kaggle/working/inventario_imagens_auditado.csv

In [88]:
import os

print(
    "Arquivo criado:",
    os.path.exists(caminho_inventario_auditado)
)

Arquivo criado: True

In [89]:
inventario_validacao = pd.read_csv(
    caminho_inventario_auditado
)

print("Tamanho após reabrir:", inventario_validacao.shape)

print("\nColunas:")
print(inventario_validacao.columns.tolist())

Tamanho após reabrir: (5856, 9)

Colunas:
['caminho', 'nome_arquivo', 'divisao_original', 'classe', 'extensao', 'sha256', 'grupo_candidato', 'duplicata_exata', 'copia_excedente']

In [90]:
print(
    "Duplicatas exatas:",
    inventario_validacao["duplicata_exata"].sum()
)

print(
    "Cópias excedentes:",
    inventario_validacao["copia_excedente"].sum()
)

print(
    "Registros disponíveis para futura modelagem:",
    (~inventario_validacao["copia_excedente"]).sum()
)

print(
    "Hashes únicos:",
    inventario_validacao["sha256"].nunique()
)

print(
    "Grupos candidatos ausentes:",
    inventario_validacao["grupo_candidato"].isna().sum()
)

Duplicatas exatas: 62
Cópias excedentes: 32
Registros disponíveis para futura modelagem: 5824
Hashes únicos: 5824
Grupos candidatos ausentes: 0

In [91]:
base_modelagem = inventario_auditado[
    ~inventario_auditado["copia_excedente"]
].copy()

print(
    "Quantidade de registros na base de modelagem:",
    len(base_modelagem)
)

print(
    "Quantidade de hashes únicos:",
    base_modelagem["sha256"].nunique()
)

Quantidade de registros na base de modelagem: 5824
Quantidade de hashes únicos: 5824

In [92]:
duplicatas_restantes = (
    base_modelagem["sha256"]
    .duplicated(keep=False)
    .sum()
)

print(
    "Arquivos ainda envolvidos em duplicatas exatas:",
    duplicatas_restantes
)

Arquivos ainda envolvidos em duplicatas exatas: 0

In [93]:
contagem_classes_modelagem = (
    base_modelagem["classe"]
    .value_counts()
)

print(contagem_classes_modelagem)

print("\nPercentuais:")
print(
    (
        base_modelagem["classe"]
        .value_counts(normalize=True)
        * 100
    ).round(2)
)

classe
PNEUMONIA    4245
NORMAL       1579
Name: count, dtype: int64

Percentuais:
classe
PNEUMONIA    72.89
NORMAL       27.11
Name: proportion, dtype: float64

In [94]:
classes_por_grupo = (
    base_modelagem
    .groupby("grupo_candidato")["classe"]
    .nunique()
)

print(
    "Maior quantidade de classes dentro de um mesmo grupo:",
    classes_por_grupo.max()
)

print(
    "Grupos associados a mais de uma classe:",
    (classes_por_grupo > 1).sum()
)

Maior quantidade de classes dentro de um mesmo grupo: 1
Grupos associados a mais de uma classe: 0

In [95]:
grupos_por_classe = (
    base_modelagem
    .groupby("classe")["grupo_candidato"]
    .nunique()
)

print("Quantidade de grupos candidatos por classe:")
print(grupos_por_classe)

print(
    "\nTotal de grupos candidatos:",
    base_modelagem["grupo_candidato"].nunique()
)

Quantidade de grupos candidatos por classe:
classe
NORMAL       1443
PNEUMONIA    2653
Name: grupo_candidato, dtype: int64

Total de grupos candidatos: 4096

In [96]:
tamanho_dos_grupos = (
    base_modelagem
    .groupby(
        ["classe", "grupo_candidato"]
    )
    .size()
)

print("Resumo do tamanho dos grupos:")

print(
    tamanho_dos_grupos
    .groupby(level="classe")
    .agg(["count", "min", "max", "mean", "median"])
    .round(2)
)

Resumo do tamanho dos grupos:
           count  min  max  mean  median
classe
NORMAL      1443    1    4  1.09     1.0
PNEUMONIA   2653    1   30  1.60     1.0

In [97]:
import sklearn

print("Versão do scikit-learn:", sklearn.__version__)

Versão do scikit-learn: 1.6.1

In [98]:
from sklearn.model_selection import StratifiedGroupKFold

print("StratifiedGroupKFold importado com sucesso.")

StratifiedGroupKFold importado com sucesso.

In [99]:
base_modelagem_folds = (
    base_modelagem
    .reset_index(drop=True)
    .copy()
)

print("Tamanho:", base_modelagem_folds.shape)

print(
    "Primeiro índice:",
    base_modelagem_folds.index.min()
)

print(
    "Último índice:",
    base_modelagem_folds.index.max()
)

Tamanho: (5824, 9)
Primeiro índice: 0
Último índice: 5823

In [100]:
sgkf = StratifiedGroupKFold(
    n_splits=10,
    shuffle=True,
    random_state=42
)

print(sgkf)

StratifiedGroupKFold(n_splits=10, random_state=42, shuffle=True)

In [101]:
base_modelagem_folds["fold"] = -1

X = base_modelagem_folds["caminho"]
y = base_modelagem_folds["classe"]
groups = base_modelagem_folds["grupo_candidato"]

for numero_fold, (_, indices_fold) in enumerate(
    sgkf.split(X, y, groups)
):
    base_modelagem_folds.loc[
        indices_fold,
        "fold"
    ] = numero_fold

In [102]:
print(
    "Registros sem fold:",
    (base_modelagem_folds["fold"] == -1).sum()
)

print("\nQuantidade de imagens por fold:")

print(
    base_modelagem_folds["fold"]
    .value_counts()
    .sort_index()
)

Registros sem fold: 0

Quantidade de imagens por fold:
fold
0    581
1    561
2    575
3    562
4    606
5    558
6    585
7    604
8    588
9    604
Name: count, dtype: int64

In [103]:
folds_por_grupo = (
    base_modelagem_folds
    .groupby("grupo_candidato")["fold"]
    .nunique()
)

print(
    "Maior quantidade de folds para um mesmo grupo:",
    folds_por_grupo.max()
)

print(
    "Grupos presentes em mais de um fold:",
    (folds_por_grupo > 1).sum()
)

Maior quantidade de folds para um mesmo grupo: 1
Grupos presentes em mais de um fold: 0

In [104]:
classes_por_fold = (
    base_modelagem_folds
    .groupby(["fold", "classe"])
    .size()
    .unstack(fill_value=0)
)

print(classes_por_fold)

classe  NORMAL  PNEUMONIA
fold
0          166        415
1          154        407
2          156        419
3          150        412
4          155        451
5          152        406
6          153        432
7          164        440
8          169        419
9          160        444

In [105]:
percentuais_por_fold = (
    classes_por_fold
    .div(classes_por_fold.sum(axis=1), axis=0)
    * 100
).round(2)

print(percentuais_por_fold)

classe  NORMAL  PNEUMONIA
fold
0        28.57      71.43
1        27.45      72.55
2        27.13      72.87
3        26.69      73.31
4        25.58      74.42
5        27.24      72.76
6        26.15      73.85
7        27.15      72.85
8        28.74      71.26
9        26.49      73.51

In [106]:
percentual_normal_global = (
    (base_modelagem_folds["classe"] == "NORMAL").mean()
    * 100
)

percentual_pneumonia_global = (
    (base_modelagem_folds["classe"] == "PNEUMONIA").mean()
    * 100
)

print(
    "NORMAL global:",
    round(percentual_normal_global, 2),
    "%"
)

print(
    "PNEUMONIA global:",
    round(percentual_pneumonia_global, 2),
    "%"
)

NORMAL global: 27.11 %
PNEUMONIA global: 72.89 %

In [107]:
desvio_normal = (
    percentuais_por_fold["NORMAL"]
    - percentual_normal_global
).abs()

print("Desvio absoluto da proporção NORMAL por fold:")
print(desvio_normal.round(2))

print(
    "\nMaior desvio encontrado:",
    round(desvio_normal.max(), 2),
    "pontos percentuais"
)

Desvio absoluto da proporção NORMAL por fold:
fold
0    1.46
1    0.34
2    0.02
3    0.42
4    1.53
5    0.13
6    0.96
7    0.04
8    1.63
9    0.62
Name: NORMAL, dtype: float64

Maior desvio encontrado: 1.63 pontos percentuais

In [108]:
base_modelagem_folds["divisao_nova"] = "treino"

base_modelagem_folds.loc[
    base_modelagem_folds["fold"] == 0,
    "divisao_nova"
] = "teste"

base_modelagem_folds.loc[
    base_modelagem_folds["fold"] == 1,
    "divisao_nova"
] = "validacao"

In [109]:
contagem_divisao_nova = (
    base_modelagem_folds["divisao_nova"]
    .value_counts()
)

print(contagem_divisao_nova)

print("\nPercentuais:")

print(
    (
        base_modelagem_folds["divisao_nova"]
        .value_counts(normalize=True)
        * 100
    ).round(2)
)

divisao_nova
treino       4682
teste         581
validacao     561
Name: count, dtype: int64

Percentuais:
divisao_nova
treino       80.39
teste         9.98
validacao     9.63
Name: proportion, dtype: float64

In [110]:
classes_por_divisao_nova = (
    base_modelagem_folds
    .groupby(
        ["divisao_nova", "classe"]
    )
    .size()
    .unstack(fill_value=0)
)

print(classes_por_divisao_nova)

classe        NORMAL  PNEUMONIA
divisao_nova
teste            166        415
treino          1259       3423
validacao        154        407

In [111]:
percentuais_classes_divisao = (
    classes_por_divisao_nova
    .div(
        classes_por_divisao_nova.sum(axis=1),
        axis=0
    )
    * 100
).round(2)

print(percentuais_classes_divisao)

classe        NORMAL  PNEUMONIA
divisao_nova
teste          28.57      71.43
treino         26.89      73.11
validacao      27.45      72.55

In [112]:
divisoes_por_grupo_final = (
    base_modelagem_folds
    .groupby("grupo_candidato")["divisao_nova"]
    .nunique()
)

print(
    "Maior número de divisões para um mesmo grupo:",
    divisoes_por_grupo_final.max()
)

print(
    "Grupos presentes em mais de uma divisão:",
    (divisoes_por_grupo_final > 1).sum()
)

Maior número de divisões para um mesmo grupo: 1
Grupos presentes em mais de uma divisão: 0

In [113]:
divisoes_por_hash_final = (
    base_modelagem_folds
    .groupby("sha256")["divisao_nova"]
    .nunique()
)

print(
    "Maior número de divisões para um mesmo SHA-256:",
    divisoes_por_hash_final.max()
)

print(
    "Hashes presentes em mais de uma divisão:",
    (divisoes_por_hash_final > 1).sum()
)

Maior número de divisões para um mesmo SHA-256: 1
Hashes presentes em mais de uma divisão: 0

In [114]:
caminho_divisao_final = (
    "/kaggle/working/base_modelagem_divisao_80_10_10.csv"
)

base_modelagem_folds.to_csv(
    caminho_divisao_final,
    index=False
)

print("Arquivo salvo em:")
print(caminho_divisao_final)

Arquivo salvo em:
/kaggle/working/base_modelagem_divisao_80_10_10.csv

In [115]:
print(
    "Arquivo criado:",
    os.path.exists(caminho_divisao_final)
)

Arquivo criado: True

In [116]:
base_divisao_validacao = pd.read_csv(
    caminho_divisao_final
)

print(
    "Tamanho após reabrir:",
    base_divisao_validacao.shape
)

print("\nColunas:")
print(
    base_divisao_validacao.columns.tolist()
)

Tamanho após reabrir: (5824, 11)

Colunas:
['caminho', 'nome_arquivo', 'divisao_original', 'classe', 'extensao', 'sha256', 'grupo_candidato', 'duplicata_exata', 'copia_excedente', 'fold', 'divisao_nova']

In [117]:
print("Quantidade por divisão:")

print(
    base_divisao_validacao["divisao_nova"]
    .value_counts()
)

print("\nTotal de registros:")
print(len(base_divisao_validacao))

print("\nGrupos atravessando divisões:")
print(
    (
        base_divisao_validacao
        .groupby("grupo_candidato")["divisao_nova"]
        .nunique()
        > 1
    ).sum()
)

print("\nHashes atravessando divisões:")
print(
    (
        base_divisao_validacao
        .groupby("sha256")["divisao_nova"]
        .nunique()
        > 1
    ).sum()
)

Quantidade por divisão:
divisao_nova
treino       4682
teste         581
validacao     561
Name: count, dtype: int64

Total de registros:
5824

Grupos atravessando divisões:
0

Hashes atravessando divisões:
0

In [118]:
import os

print(os.path.exists(
    "/kaggle/working/inventario_imagens_auditado.csv"
))

print(os.path.exists(
    "/kaggle/working/base_modelagem_divisao_80_10_10.csv"
))

True
True

In [119]:
from IPython.display import FileLink, display

display(
    FileLink(
        "/kaggle/working/inventario_imagens_auditado.csv"
    )
)

display(
    FileLink(
        "/kaggle/working/base_modelagem_divisao_80_10_10.csv"
    )
)

/kaggle/working/inventario_imagens_auditado.csv

/kaggle/working/base_modelagem_divisao_80_10_10.csv